export enum AlarmWqm {
    Idle = 0,
    Chlorine = 1,
    AcidityPH = 2,
    Oxidation = 3,
    ChlorineEmpty = 4,
    AcidityPHEmpty = 5,
    WaterflowShortage = 6,
    WaterflowClearWaterShortage = 7,
    DisinfectionError = 8,
    FilterCleaningOngoing = 9,
    HeatingOperationOngoing = 10,
    FilterPumpOperationOngoing = 11,
    FreshwaterOperationOngoing = 12,
    DryProtectionOperationOngoing = 13,
    WaterTankEmpty = 14,
    WaterTankLevelUnknown = 15,
    WaterTankFull = 16,
    CollectiveDisorder = 17,
    UnknownEvent = 254
}
