export enum AlarmPm {
    Idle = 0,
    PowerApplied = 1,
    AcMainsDisconnected = 2,
    AcMainsReconnected = 3,
    Surge = 4,
    VoltageDropDrift = 5,
    OverCurrent = 6,
    OverVoltage = 7,
    Overload = 8,
    LoadError = 9,
    ReplaceBatterySoon = 10,
    ReplaceBatteryNow = 11,
    BatteryCharging = 12,
    BatteryFullyCharged = 13,
    ChargeBatterySoon = 14,
    ChargeBatteryNow = 15,
    BackupBatteryLow = 16,
    BatteryFluidLow = 17,
    BackupBatteryDisconnected = 18
}
